### ISSUE TITLE
FUSE Width split no calculating correctly in 1 to 2 copied orders

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#229]
Price goes down when you go from 2 Width splits to 3 Width splits

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b548351a-04fb-414f-b122-875bb2d68d97)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/bff7551b-12c0-453b-a2a3-a2a90cef5149)

**Comment by Reyzerbit** [comment]
@daniel11088 this isn't caused by 1.0 to 2.0 conversion. Math has always resulted in more splits causing different prices. If you want to go over math specifically, we can. Additionally, the first split isn't even valid. Anytime there is a red 'error' on a product, the pricing should be ignored in general, as the pricing has exceeded the bounds of our calculations.
