### ISSUE TITLE
Bug: Bison Products '-BSN' allow you to add zinc patina as a finish which yields incorrect pricing

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#394]
on a test proposal add: 
BISON-962420-BSN
BISON-962420-PAT

Attempt to add zinc patina finish to both planter builds.
BISON-962420-BSN (Bison Zinc Patina): $1940.40 marked as a pre-design
BISON-962420-PAT (Oxidized Zinc Patina): $2240.70 marked as pre-design [this is correct pricing]

-why do we have 2 zinc patina finishes? 
-why does 'bison zinc patina' not trigger the -PAT part #?
-why is the bison part # convention different than Ore part #s? For our product we just add an A1100 for example, the finish then changes the price - this is the same for pre-designed fuse.

**Comment by Reyzerbit** [comment]
Looked into this with Jake Drake, it appears he made a Bison finish called "Bison Zinc Patina" about 3 months ago. He says its because Bison wanted the finish to show up as "Bison Zin Patina" and not "Oxidized Zinc Patina", so he made an item identical to Zinc Patina that shows the new name. I showed him how to change configuration to make it behave properly in Ore3D. He will close this when issue is resolved.

**Comment by MattIsrael** [comment]
Thanks for jumping on this Batista!

[Ore Logo]
Matt Israel
Estimating Manager

***@***.******@***.***>
→ 385.249.1980

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>

**Comment by Reyzerbit** [comment]
@jdrake89 this done?

**Comment by jdrake89** [comment]
No the products are still showing the -BSN and -PAT at the end.

You said that was something you had to take care of.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
