### ISSUE TITLE
Shape Codes

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#7]
Conversation Required

1. What/where is the current list of Shape Codes (pomos are split out on Bug Ore-Design/Ore-3D-Reports-Changelog#759) they are not on the list I received.
2. What/where are the current list of option(BOM) families (ex. bowl, dish, tube, etc); child shape codes (lids, pans, drip trays)
3. Who determines when a new shape code is needed? 
4. Who generates & validates the shape code formulas (ESTIMATING should generate & be in charge of validation) - delivers to IT for implementation.

**Comment by Reyzerbit** [comment]
@mxidis any insights on this before I answer anything? Perhaps in regards to possible changes in Company SOP ownership with Ore3D et al?

**Comment by Reyzerbit** [comment]
@mxidis confirmed no imminent changes, so here are your answers:

1. There isn't an actual storage place. We have some old lists, but in Ore3D 2.0, "ShapeCodes" are abstract and are purely a collection of mathematical functions. I can still get you a list of what these ShapeCodes are, but it is something I'll have to retrieve for you manually any time you need an update.
2. Location of options:
   a. BOM families are located in Netsuite, but not sure if you have access to the list. [Customization > Lists, Records, and Fields > Record Types > Ore3D BOM Type](https://3619299.app.netsuite.com/app/common/custom/custrecord.nl?id=777&e=T)
   b. Same as ShapeCodes answer
3. The company as a whole, but primarily Supply Chain/Operations/Finance. Any time the way that BOMs and routing times are calculated differently when considering the shop floor and actual materials used, as well as any other processes involved, a new ShapeCode needs to be created.
4. Currently, formulas are generated per actual mathematical calculation of the product. Think of it as pseudo-CAD. We use the base formula that you provided for FAB time, via weld inches, but otherwise all formulas are based on square footage of the product. Square footage formulas are a literal geometric formula to create the shapes we produce at Ore, and those formulas are not subject to de-complication. I'm happy to discuss those formulas and demonstrate how they are accurate at any point.

- cosigned by @mxidis
